// vue/src/App.vue
<template>
    <div className="vue-container">
        <img src="https://upload.wikimedia.org/wikipedia/commons/9/95/Vue.js_Logo_2.svg" alt="Vue logo"/>

        <div className="vue-counter-container">
            <div className="vue-counter vue-counter-minus" @click="decrement">
                -
            </div>

            <div className="vue-counter vue-counter-value" @click="reset">
                {{counter}}
            </div>

            <div className="vue-counter vue-counter-plus" @click="increment">
                +
            </div>
        </div>
    </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
    name: 'App',
    data() {
        return {
            counter: 0
        }
    },
    methods: {
        increment() {
            this.counter++;
        },
        decrement() {
            this.counter--;
        },
        reset() {
            this.counter = 0;
        }
    },
});
</script>

<style>
.vue-container {
    height: calc(100vh - 65px);
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
}

.vue-container img {
    width: 80px;
    animation: rotation 5s infinite linear;
    margin-bottom: 15px;
}

@keyframes rotation {
    from {
        transform: rotate(0deg);
    }
    to {
        transform: rotate(359deg);
    }
}

.vue-counter-container {
    display: flex;
    align-items: center;
    justify-content: center;
}

.vue-counter {
    border-radius: var(--border-radius);
    font-size: var(--font-size-medium);
    width: 25px;
    height: 25px;
    display: flex;
    align-items: center;
    justify-content: center;
    color: #ffffff;
    font-weight: 600;
    margin: 0px 5px;
    cursor: pointer;
}

.vue-counter-minus {
    background-color: red;
}

.vue-counter-value {
    background-color: cyan;
}

.vue-counter-plus {
    background-color: green;
}

</style>

// angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'mfe';
  counter = 0;
  increment() {
    this.counter++;
  }
  decrement() {
    this.counter--;
  }
  reset() {
    this.counter = 0;
  }
}

<div class="angular-container">
  <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Angular_full_color_logo.svg/512px-Angular_full_color_logo.svg.png?20160527092314" alt="Angular Logo" />

  <div class="angular-counter-container">
      <div class="angular-counter angular-counter-minus" (click)="decrement()">
          -
      </div>

      <div class="angular-counter angular-counter-value" (click)="reset()">
          {{counter}}
      </div>

      <div class="angular-counter angular-counter-plus" (click)="increment()">
          +
      </div>
  </div>
</div>

<router-outlet></router-outlet>
